[program:gobackend]
directory=/root/scorpio/gobackend
command=/root/scorpio/gobackend/gobackend
autostart=true
autorestart=true
stderr_logfile=/var/log/gowebsocks.err.log
stdout_logfile=/var/log/gowebsocks.out.log
user=root
environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin",DEBUG=0,APP_ENV=product
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=7

stderr_logfile_maxbytes=50MB
stderr_logfile_backups=7